### ISSUE TITLE
modelutility_v2.py is missing

### ISSUE THREAD

**Issue by wongjoel** [YuchiSun/SUNSET#1]
The supplementary data for the associated article references helper functions in `model_utility_v2.py`. This file appears to be missing. In particular, the following import statement at the top of `CNN_1.0_Baseline.ipynb` will fail: `from modelutility_v2 import *`. I assume the file is missing from this repo.

**Comment by YuchiSun** [comment]
@wongjoel sorry for the loooong delay. Just dug into my piles and added the utility script. This should be the correct script file, but it may not work off the shelf as the project is more than 2 years ago. Let me know how it goes.
